// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_record_breaker = "CgkIgJubrdEFEAIQCw"; // <GPGSID>
        public const string achievement_welcome = "CgkIgJubrdEFEAIQBA"; // <GPGSID>
        public const string achievement_wall_smash = "CgkIgJubrdEFEAIQAQ"; // <GPGSID>
        public const string achievement_quality_esports_gameplay = "CgkIgJubrdEFEAIQCg"; // <GPGSID>
        public const string achievement_no_walls_but_balls = "CgkIgJubrdEFEAIQCQ"; // <GPGSID>
        public const string achievement_protilter = "CgkIgJubrdEFEAIQBQ"; // <GPGSID>
        public const string achievement_whoa_holy = "CgkIgJubrdEFEAIQAg"; // <GPGSID>
        public const string leaderboard_walls_destroyed = "CgkIgJubrdEFEAIQAw"; // <GPGSID>
        public const string achievement_proswiper = "CgkIgJubrdEFEAIQBg"; // <GPGSID>
        public const string achievement_air_ball = "CgkIgJubrdEFEAIQBw"; // <GPGSID>
        public const string achievement_lol = "CgkIgJubrdEFEAIQCA"; // <GPGSID>

}

